WEB_HW_10/WEB_HW_10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quotes.urls')),
    path("users/", include("users.urls")),
]

WEB_HW_10/quotes/urls.py
from django.urls import path
from . import views

app_name = "quotes"

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:page>', views.index, name="index_paginate"),
    path('author/<str:fullname>', views.AuthorView.as_view(), name="author_info"),
    path('createTag', views.CreateTagView.as_view(), name="createTag"),
    path('createAuthor', views.CreateAuthorView.as_view(), name="createAuthor"),
    path('createQuote', views.CreateQuoteView.as_view(), name="createQuote"),
]

WEB_HW_10/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_views
from .views import UserRegisterView

urlpatterns = [
    path('register/', UserRegisterView.as_view(), name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="users/login.html", next_page="quotes:index"), name="login"),
    path('logout/', auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout"),
]

WEB_HW_10/quotes/models.py
from django.db import models


# Create your models here.
class Author(models.Model):
    fullname = models.SlugField()  #models.CharField(max_length=100)
    born_date = models.DateField()
    born_location = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    tags = models.ManyToManyField(Tag)

WEB_HW_10/users/models.py
from django.db import models

# Create your models here.

WEB_HW_10/quotes/forms.py
from django import forms
from django.forms import models

from .models import Tag, Author, Quote


class TagForm(models.ModelForm):
    class Meta:
        model = Tag
        fields = ["name"]


class AuthorForm(models.ModelForm):
    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]
        widgets = {
            "born_date": forms.DateInput()
        }


class QuoteForm(models.ModelForm):
    class Meta:
        model = Quote
        fields = ["quote", "author", "tags"]
        widgets = {
            "tag": forms.CheckboxSelectMultiple(),
        }

WEB_HW_10/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class UserRegistrationForm(UserCreationForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

WEB_HW_10/quotes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.views.generic import CreateView, DetailView

from .forms import TagForm, AuthorForm, QuoteForm
from .models import Author, Tag, Quote
from django.core.paginator import Paginator


# Create your views here.

def index(request, page=1):
    quotes = Quote.objects.all()
    item_per_page = 10
    paginator = Paginator(list(quotes), item_per_page)
    quote_on_page = paginator.page(page)
    return render(request, template_name="quotes/index.html", context={"quotes": quote_on_page})


class CreateTagView(LoginRequiredMixin, CreateView):
    login_url = "login"
    model = Tag
    template_name = "quotes/createTag.html"
    form_class = TagForm
    success_url = "createTag"


class CreateAuthorView(LoginRequiredMixin, CreateView):
    login_url = "login"
    model = Author
    template_name = "quotes/createAuthor.html"
    form_class = AuthorForm
    success_url = "createAuthor"


class CreateQuoteView(LoginRequiredMixin, CreateView):
    login_url = "login"
    model = Quote
    template_name = "quotes/createQuote.html"
    form_class = QuoteForm
    success_url = "createQuote"


# def author_view(request, fullname):
#     author = Author.objects.get(fullname=fullname)
#     return render(request, template_name="quotes/authorInfo.html", context={"author": author})

class AuthorView(DetailView):
    model = Author
    template_name = "quotes/authorInfo.html"
    context_object_name = "author"

    def get_object(self):
        return Author.objects.get(fullname=self.kwargs['fullname'])

WEB_HW_10/users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import UserRegistrationForm


# Create your views here.
class UserRegisterView(CreateView):
    form_class = UserRegistrationForm
    template_name = "users/register.html"
    success_url = reverse_lazy('login')

WEB_HW_10/quotes/templates/quotes/authorInfo.html
{% extends "base.html" %}
{% block title %}Author{% endblock %}
{% block content %}
        <div class="author-details">
        <h3 class="author-title">{{ author.fullname }}</h3>
        <p><strong>Born:</strong> <span class="author-born-date">{{ author.born_date }}</span>
            <span class="author-born-location">{{ author.born_location }}</span></p>
        <p><strong>Description:</strong></p>
        <div class="author-description">
            {{ author.description }}
        </div>
        </div>
{% endblock %}

WEB_HW_10/quotes/templates/quotes/createAuthor.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title %} Create Author {% endblock %}
{% block content %}
<h2> Create Author </h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary"> Create </button>
</form>
{% endblock %}

WEB_HW_10/quotes/templates/quotes/createQuote.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title %} Create Quote {% endblock %}
{% block content %}
<h2> Create Quote </h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary"> Create </button>
</form>
{% endblock %}

WEB_HW_10/quotes/templates/quotes/createTag.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title %} Create Tag {% endblock %}
{% block content %}
<h2> Create Tag </h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary"> Create </button>
</form>
{% endblock %}

WEB_HW_10/quotes/templates/quotes/index.html
{% extends 'base.html' %}
{% block title %}Quotes{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
        <span class="text" itemprop="text">
            {{quote.quote}}
        </span>
        <span>by <small class="author" itemprop="author">{{ quote.author.fullname }}</small>
        <a href="/author/{{quote.author.fullname}}">(about)</a>
        </span>
        <div class="tags">
            Tags:
            {% for tag in quote.tags.all %}
            <a class="tag" href="#">{{tag.name}}</a>
            {% endfor %}


        </div>
    </div>
    {% endfor %}
        <nav>
            <ul class="pager">
                <li class="previous">
                    <a class = "{% if not quotes.has_previous %} disabled {% endif %}"
                       href="{% if quotes.has_previous %} {% url 'quotes:index_paginate' quotes.previous_page_number %} {% else %} # {% endif %}"><span aria-hidden="true">←</span> Previous</a>
                </li>

                <li class="next">
                    <a class = "{% if not quotes.has_next %} disabled {% endif %}"
                            href="{% if quotes.has_next %} {% url 'quotes:index_paginate' quotes.next_page_number %} {% else %} # {% endif %}">Next <span aria-hidden="true">→</span></a>
                </li>
            </ul>
        </nav>
    </div>

</div>
{% endblock %}

WEB_HW_10/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'quotes/style.css'%}">
    <title>{% block title %}Title{% endblock %}</title>
</head>
<body>
<div class="row header-box">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                </h1>
            </div>
            <div class="col-md-4">
                    {% if user.is_authenticated %}
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button class="tag" type="submit">Logout</button>
                        </form>
                        <a class="tag" href="{% url 'quotes:createTag' %}">Add Tag</a>
                        <a class="tag" href="{% url 'quotes:createAuthor' %}">Add Author</a>
                        <a class="tag" href="{% url 'quotes:createQuote' %}">Add Quote</a>
                    {% else %}
                        <a class="tag" href="{% url 'login' %}">Login</a>
                        <a class="tag" href="{% url 'register' %}">Register</a>
                    {% endif %}
            </div>
        </div>
{% block content %} {% endblock %}
</body>
</html>

WEB_HW_10/users/templates/users/login.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title %} Login {% endblock %}
{% block content %}
<h2> Login </h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary"> Login </button>
</form>
{% endblock %}

WEB_HW_10/users/templates/users/logout.html
{% extends 'base.html'%}
{% block title %} LogOut {% endblock %}
{% block content %}
{% csrf_token %}
<h2> You logged out now </h2>
<a href="{% url 'login' %}" > Login </a>
{% endblock %}

WEB_HW_10/users/templates/users/register.html
{% extends 'base.html'%}
{% load crispy_forms_tags %}
{% block title %} User registration {% endblock %}
{% block content %}
<h2> Registration </h2>
<form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="btn btn-primary"> Register </button>
</form>
{% endblock %}